apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobiles-deployment
  labels:
    app: mobiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobiles
  template:
    metadata:
      labels:
        app: mobiles
    spec:
      containers:
      - name: mobiles
        image: 876042377013.dkr.ecr.us-west-2.amazonaws.com/shopping-site-mobiles:7670a8a5cf5321de8af35f9489b2f99694a34be2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mobiles-service
  labels:
    app: mobiles
spec:
  type: ClusterIP
  selector:
    app: mobiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
