apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
  labels:
    app: sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
      - name: sports
        image: 678874287739.dkr.ecr.us-west-2.amazonaws.com/shopping-site-sports:5a9f3aa867e72f84187157e620ba7ecea753d3c4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sports-service
  labels:
    app: sports
spec:
  type: ClusterIP
  selector:
    app: sports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
