apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: 678874287739.dkr.ecr.us-west-2.amazonaws.com/shopping-site-books:97dcd19a583c30b1aa7d69033c7b9d11ecc55686
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
